global:
  scrape_interval:     10s
  evaluation_interval: 10s

  external_labels:
    monitor: 'promswarm'

rule_files:
  - "node.rules.yml"
  - "task.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'traefik'
    dns_sd_configs:
    - names:
      - 'tasks.reverse-proxy'
      type: 'A'
      port: 8082
