#!/bin/bash

set +x -e

service_name="tpd-build"
docker_cmd="docker"
maven_repo_cache="tpd-maven-repo"
image_name="maven:3.6.3-jdk-13"

source script/setenv.sh


if [ "$(container_exists ${service_name})" != "" ]; then
    echo "- Remove Container : ${service_name}"
    ${docker_cmd} rm $(docker ps -aq --filter name=${service_name} )
fi

if [ "$(volume_exists ${maven_repo_cache})" = "" ]; then
    echo "- Create Volume : ${maven_repo_cache}"
    ${docker_cmd} volume create --name ${maven_repo_cache}
fi

${docker_cmd} run -it --rm \
    -v "${PWD}":/usr/src -v ${maven_repo_cache}:/root/.m2 \
    -w /usr/src ${DOCKER_OPTIONS} \
    ${image_name} \
    mvn dependency:resolve -Pfull

${docker_cmd} run -it --rm --name ${service_name} \
    -v "${PWD}":/usr/src -v ${maven_repo_cache}:/root/.m2 \
    -w /usr/src ${DOCKER_OPTIONS} \
    ${image_name} \
    mvn "$@" -Dtoolchains.disabled=true
