{
 "title": "Graphite Server (Carbon Metrics)",
 "description": "Graphite Carbon Cache Metrics",
 "tags": [ "Graphite" ],
 "time": {
  "from": "now-6h",
  "now": true,
  "to": "now"
 },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Cache", "query": "carbon.agents.*" }
  ]
 },
 "panels": [
  {
   "title": "Metrics Received (current)",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(carbon.agents.*.metricsReceived)"
    }
   ]
  },
  {
   "title": "Metrics Created (Avg)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(carbon.agents.*.creates)"
    }
   ]
  },
  {
   "title": "Metric Update Time (Avg)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(averageSeries(carbon.agents.*.avgUpdateTime), 1000)"
    }
   ]
  },
  {
   "title": "Total Graphite CPU (current)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "sumSeries(carbon.*.*.cpuUsage)" }
   ]
  },
  {
   "title": "Total Metrics Received vs Commited Points",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "metics/min" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.agents.*.metricsReceived), 'Receieved')"
    },
    {
     "target": "alias(sumSeries(carbon.agents.*.committedPoints), 'Committed Points')"
    }
   ]
  },
  {
   "title": "Update Operations vs. Creates & CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Updates" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.agents.*.updateOperations), 'Updates')"
    },
    {
     "target": "alias(sumSeries(carbon.agents.*.creates), 'Creates')"
    },
    {
     "target": "alias(averageSeries(carbon.agents.*.cpuUsage), 'CPU')"
    }
   ]
  },
  {
   "title": "Metrics Received vs CPU Load Avg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Received/min" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.agents.*.metricsReceived), 'Received')"
    },
    {
     "target": "alias(sumSeries(carbon.*.*.cpuUsage), 'CPU')"
    }
   ]
  },
  {
   "title": "Metrics Created vs Metrics Committed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "created/min" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.agents.*.creates), 'Created')"
    },
    {
     "target": "alias(sumSeries(carbon.agents.*.committedPoints), 'Committed Points')"
    }
   ]
  },
  {
   "title": "Metrics Received (per cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "metics/min" }
   ],
   "targets": [
    {
     "target": "aliasByNode(carbon.agents.$Cache.metricsReceived, 2, 3)"
    }
   ]
  },
  {
   "title": "Average Update Time (per cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "ms", "label": "Update Time" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(carbon.agents.$Cache.avgUpdateTime, 1000), 2, 3)"
    }
   ]
  },
  {
   "title": "Points per Update (per Cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "points" }
   ],
   "targets": [
    {
     "target": "aliasByNode(carbon.agents.$Cache.pointsPerUpdate, 2, 3)"
    }
   ]
  },
  {
   "title": "Queries (per Cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Cache Queries" }
   ],
   "targets": [
    {
     "target": "aliasByNode(carbon.agents.$Cache.cache.queries, 2, 3)"
    }
   ]
  },
  {
   "title": "CPU Usage (per Cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(carbon.agents.$Cache.cpuUsage, 2, 3)"
    }
   ]
  },
  {
   "title": "Memory Usage (per Cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(carbon.agents.$Cache.memUsage, 2, 3)"
    }
   ]
  },
  {
   "title": "Cache Size (per Cache)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Cache Datapoints" }
   ],
   "targets": [
    {
     "target": "aliasByNode(carbon.agents.$Cache.cache.size, 2, 3)"
    }
   ]
  }
 ]
}