{
 "title": "TPD Submission Tool",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(tpd.os.process.cpu.load, 2)"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByNode(tpd.jvm.memory.heap.max, 3, 4)"
    },
    {
     "target": "aliasByNode(tpd.jvm.memory.heap.used, 3, 4)"
    },
    {
     "target": "aliasByNode(tpd.jvm.memory.heap.committed, 3, 4)"
    },
    {
     "target": "aliasByNode(tpd.jvm.memory.non-heap.used, 3, 4)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "target": "aliasByNode(tpd.jvm.memory.total.max, 4)"
    },
    {
     "target": "aliasByNode(tpd.jvm.memory.total.used, 4)"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(tpd.InstrumentedRequest.activeRequests.count, 2)"
    }
   ]
  },
  {
   "title": "Requests duration (ms)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(tpd.InstrumentedRequest.requests.p*)"
    }
   ]
  },
  {
   "title": "Average Response Codes  on 1 min  (calls/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(tpd.InstrumentedRequest.responseCodes.*.m1_rate, 3)"
    }
   ]
  },
  {
   "title": "Threads Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(tpd.jvm.threads.count, 3)"
    },
    {
     "target": "aliasByNode(tpd.jvm.threads.runnable.count, 3)"
    },
    {
     "target": "aliasByNode(tpd.jvm.threads.waiting.count, 3)"
    },
    {
     "target": "aliasByNode(tpd.jvm.threads.timed_waiting.count, 3)"
    },
    {
     "target": "aliasByNode(tpd.jvm.threads.deadlock.count, 3)"
    },
    {
     "target": "aliasByNode(tpd.jvm.threads.blocked.count, 3)"
    }
   ]
  },
  {
   "title": "Database Data Source",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(tpd.datasource.connection.total.*, 2, 4)"
    },
    {
     "target": "aliasByNode(tpd.datasource.statement.execute.avg, 2, 4)"
    }
   ]
  },
  {
   "title": "Error Logs (events/second)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(tpd.ch.qos.logback.core.Appender.error.m*)"
    }
   ]
  }
 ]
}