#-----------------------------------------------------------------------------------------------------------------------
# The app.home configuration must be set and specifies the directory in which application will store its data files.
# This must be set to an absolute path. Relative paths are not allowed.
# Ensure that only one application instance uses the selected Home foled.
#
###########################
# Note for Windows Users
###########################
#
# NOTE : If you are using Windows, you will need to use double \ characters, for example c:\app-home should be written
# as c:\\app-home
#
# You can also use Unix like paths which Java/Portal can handle. eg c:/app-home
#-----------------------------------------------------------------------------------------------------------------------
app:
  home: 
  log:
    # log level : (DEBUG|TRACE|INFO|WARN|ERROR)
    loglevel: WARN
    fullStackTraces: true
  security:
    authentication:
      directory:
        # LDAP directory that you will connect to.
        activeDirectory:
          name: "PMI Active Directory"
          authenticationOnly: false
          domain: PMINTL.NET
          hostname: ldap.app.pmi
          port: 389 # ldap or 636 ldaps
          username: s-pmirdldapsync
          password: paswds.987
          ldapSchema:
            baseDn: DC=PMINTL,DC=NET
            additionalGroupDn: (cn=PMI CH 1002 UR RD EUTPD*)
            additionalUserDn: (objectClass=user)

  # Domibus Configuration
  #-----------------------------------------------------------------------------------------------------------------------
  domibus:
    enable: true
    connectionType: Ws
    url: https://pmpsa-as4-int.app.pmi/domibus
    action: SubmitRequest
    serviceType: "e-delivery"
    service: "http://ec.europa.eu/e-delivery/services/tobacco-ecig-reporting"
    originalSender: urn:oasis:names:tc:ebcore:partyid-type:unregistered:C1
    finalRecipient: urn:oasis:names:tc:ebcore:partyid-type:unregistered:C4
    partyIdType: urn:oasis:names:tc:ebcore:partyid-type:unregistered:EUCEG
    keyPairAlias:
    trustedCertificateAlias:
    jmsOptions:
      url: tcp://pmpsa-as4-int.app.pmi:6161
    
  elasticsearch:
    enableMemoryLock: true
