version: "3.9"
services:
  adminer:
    image: adminer
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adminer-http.rule=Host(`adminer.${DOMAIN}`)"
        - "traefik.http.routers.adminer-http.entrypoints=http"
        - "traefik.http.routers.adminer-http.middlewares=https-redirect"
        - "traefik.http.routers.adminer-https.rule=Host(`adminer.${DOMAIN}`)"
        - "traefik.http.routers.adminer-https.entrypoints=https"
        - "traefik.http.routers.adminer-https.tls=true"
        - "traefik.http.services.adminer.loadbalancer.server.port=8080"
    networks:
      - backend
      - discovery
