version: "3.9"
services:
  db:
    image: "mysql:${DOMIBUS_MYSQL_VERSION}"
    hostname: db
    command:
      - "mysqld"
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_bin"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: ${DOCKER_RESTART_POLICY:-on-failure}
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    configs:
      - source: myql_config
        target: /etc/mysql/conf.d/config-file.cnf
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_USER=${DOMIBUS_DATABASE_USERNAME}"
      - "MYSQL_PASSWORD=${DOMIBUS_DATABASE_PASSWORD}"
      - "MYSQL_DATABASE=domibus"
    healthcheck:
        test: ["CMD", "mysqladmin" , "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
      - "dbdata:/var/lib/mysql:delegated"
    networks:
      - backend
  domibus:
    image: "domibus/domibus:${DOMIBUS_MAJOR_VERSION}"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: ${DOCKER_RESTART_POLICY:-on-failure}
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 712M
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.domibus-http.rule=HostRegexp(`domibus.${DOMAIN}`,`domibus-{dashed-ip:.*}.${DOMAIN}`)"
        - "traefik.http.routers.domibus-http.entrypoints=http"
        - "traefik.http.routers.domibus-http.middlewares=https-redirect@file"
        - "traefik.http.routers.domibus-https.rule=HostRegexp(`domibus.${DOMAIN}`,`domibus-{dashed-ip:.*}.${DOMAIN}`)"
        - "traefik.http.routers.domibus-https.tls.domains[0].main=domibus.${DOMAIN}"
        - "traefik.http.routers.domibus-https.tls.domains[0].sans=domibus-*.${DOMAIN}"
        - "traefik.http.routers.domibus-https.entrypoints=https"
        - "traefik.http.routers.domibus-https.tls=true"
        - "traefik.http.services.domibus.loadbalancer.server.port=8080"
    environment:
      - "DATABASE_SERVER=db"
      - "DATABASE_SCHEMA=domibus"
      - "DATABASE_PORT=3306"
      - "DATABASE_USERNAME=${DOMIBUS_DATABASE_USERNAME}"
      - "DATABASE_PASSWORD=${DOMIBUS_DATABASE_PASSWORD}"
      - "CHECK_DEFAULT_PASSWORD=false"
      - "CERT_ALIAS=${DOMIBUS_CERT_BLUE_ALIAS}"
      - "DOMIBUS_MODE=test"
    entrypoint: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "60s", "/entrypoint.sh", "run" ]
    volumes:
      - "home:/usr/share/domibus/home"
    networks:
      backend:
        aliases:
          - "domibus-blue"
          - "blue_hostname"
      discovery:
  updater:
    image: "domibus/updater:${DOMIBUS_MAJOR_VERSION}"
    configs:
      - source: pmode
        target: /pmodes/pmode.xml
    entrypoint: [
      "dockerize",
       "-wait",
      "tcp://domibus:8080",
      "-timeout",
      "320s",
      "/entrypoint.sh",
      "pmode",
      "--server=http://domibus:8080",
      "--username=admin",
      "--password=123456",
      "--filename=/pmodes/pmode.xml"
    ]
    deploy:
      restart_policy:
        condition: none
    networks:
      - backend
networks:
  backend:
    driver: overlay
  discovery:
    external: true
volumes:
  dbdata: {}
  home: {}
configs:
  myql_config:
    file: ${PWD}/etc/mysql/conf.d/config-file.cnf
  pmode:
    file: ${PWD}/etc/domibus/pmodes/domibus-gw-sample-pmode-blue.xml
